cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/config/routes.rb
Cookbook3::Application.routes.draw do
  resources :categories

  resources :recipes

  root :to => 'categories#index'

end

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes

  validates :name, :presence => true
end

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category

  validates :title, :presence => true
  validates :description, :presence => true
  validates :instructions, :presence => true
  validates :category, :presence => true

end

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  ***************

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

hi

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
*****
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :ok }
    end
  end
end

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/helpers/application_helper.rb
module ApplicationHelper
end

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/helpers/categories_helper.rb
module CategoriesHelper
end

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/helpers/recipes_helper.rb
module RecipesHelper
end

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook3</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Online Cookbook</h1>

<%= yield %>

<p>
   <%= link_to "Show all recipes", recipes_path %>
   <%= link_to "Show all categories", categories_path %>
</p>

</body>
</html>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= select("recipe", "category_id", Category.find(:all).collect{ |c| [ c.name, c.id] }) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br />
    <%= f.text_area :instructions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Instructions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.title %></td>
    <td><%= recipe.description %></td>
    <td><%= recipe.instructions %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

cookbook_changes2/barik-csc517_cookbook3-325ff9f/barik-csc517_cookbook3-325ff9f/app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @recipe.title %>
</p>

<p>
  <b>Description:</b>
  <%= @recipe.description %>
</p>

<p>
  <b>Instructions:</b>
  <%= @recipe.instructions %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>